networks:
  python-kafka-net:
    driver: bridge
  
services: 
  db:
    # based on https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
    image: postgres:12.19
    restart: always 
    networks:
      - python-kafka-net
    environment:
      # needed although not set
      - POSTGRES_PASSWORD=""
    volumes: 
      - pg_data:/var/lib/postgresql/data  
    ports:
      - "5342:5342"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - python-kafka-net
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    networks:
      - python-kafka-net
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OTHER_CONFIG=later 
    depends_on:
      - zookeeper 

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  pg_data: 
    driver: local